import tkinter as tk

window = tk.Tk()
window.title('Calculator')
window.geometry('350x350')
window.resizable(False, False)

button_1 = tk.Button(window, text='1')
button_2 = tk.Button(window, text='2')
button_3 = tk.Button(window, text='3')
button_4 = tk.Button(window, text='4')
button_5 = tk.Button(window, text='5')
button_6 = tk.Button(window, text='6')
button_7 = tk.Button(window, text='7')
button_8 = tk.Button(window, text='8')
button_9 = tk.Button(window, text='9')
button_0 = tk.Button(window, text='0')
button_add = tk.Button(window, text='+')
button_subtract = tk.Button(window, text='-')
button_multiply = tk.Button(window, text='*')
button_divide = tk.Button(window, text='/')
button_equal = tk.Button(window, text='=')
button_clear = tk.Button(window, text='Clear')
button_quit = tk.Button(window, text='Quit')

# place buttons
button_1.grid(row=0, column=0)
button_2.grid(row=0, column=1)
button_3.grid(row=0, column=2)
button_4.grid(row=1, column=0)
button_5.grid(row=1, column=1)
button_6.grid(row=1, column=2)
button_7.grid(row=2, column=0)
button_8.grid(row=2, column=1)
button_9.grid(row=2, column=2)
button_0.grid(row=3, column=1)
button_add.grid(row=4, column=0)
button_subtract.grid(row=4, column=1)
button_multiply.grid(row=4, column=2)
button_divide.grid(row=5, column=0)
button_equal.grid(row=5, column=1)
button_clear.grid(row=5, column=2)
button_quit.grid(row=6, column=0, columnspan=3)

window.mainloop()
